version: 0.2

phases:
  build:
    commands:
      - aws s3 rm s3://snake.sbroadhurst.net --recursive
      - aws s3 cp . s3://snake.sbroadhurst.net --recursive --acl public-read
      - aws s3 rm s3://snake.sbroadhurst.net/.git --recursive
      - aws s3 rm s3://snake.sbroadhurst.net/builtspec.yml
artifacts:
  files: build/**/*
